apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: ${REGISTRY}/tinyhats_reinvent/frontend-service
          ports:
            - containerPort: 3000
          env:
            - name: NEW_RELIC_LICENSE_KEY
              value: "${NEW_RELIC_LICENSE_KEY}"
            - name: NEW_RELIC_METADATA_REPOSITORY_URL
              value: "${REPOSITORY_URL}"
            - name: NEW_RELIC_METADATA_COMMIT
              value: "${COMMIT}"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000
  type: NodePort
